spring.application.name=hackhub

# Database - Nota il punto prima di /data
spring.datasource.url=jdbc:h2:file:./data/hackhubDb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=gondor
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# JWT
app.jwt.secret=mySuperSecretKey12345678901234567890
app.jwt.expiration-ms=86400000

