package com.project.hackhub.model.utente.state;

public enum Permission {
    CAN_ADD_MENTOR, CAN_ADD_JUDGE, CAN_INVITE_USERS, CAN_MANAGE_INFRACTIONS,
    CAN_MODIFY_HACKATHON, CAN_GRADE_SUBMISSION, CAN_CREATE_TEAM, CAN_PROPOSE_CALL,
    CAN_REPORT_INFRACTION, CAN_UNSUBSCRIBE_TEAM, STAFF_PERMISSION,CAN_SEND_AID_REQUEST,
    DETAILED_INFO, CAN_MODIFY_LEADER, TEAM_PERMISSION, CAN_MANAGE_STAFF, CAN_MANAGE_TEAMS,
    CAN_DELETE_HACKATHON, CAN_EDIT_HACKATHON, CAN_CANCEL_INVITATION, CAN_SEND_SUBMISSION,
    CAN_EXPEL_TEAM, CAN_PENALIZE_TEAM, CAN_CHOOSE_WINNER, CAN_PROCLAIM_WINNER
}
