package com.project.hackhub.model.utente.state;

public enum Permission {
    CAN_ADD_MENTOR, CAN_ADD_JUDGE, CAN_SUBSCRIBE_TEAM, CAN_INVITE_USERS, CAN_MANAGE_INFRACTIONS, CAN_MODIFY_HACKATHON, CAN_GRADE_SUBMISSION, CAN_CREATE_TEAM, CAN_PROPOSE_CALL, CAN_REPORT_INFRACTION
}
