package com.project.hackhub.observer;

public enum EventType {
    ELIMINAZIONE_HACKATHON, NUOVO_LEADER, SCELTA_VINCITORE, INVITO_UTENTE,
    RIMOZIONE_DA_TEAM, ELIMINAZIONE_TEAM, PROCLAMAZIONE_VINCITORE
}
